modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="everything_totem"
version="1.0.0"
displayName="万物皆可图腾"
logoFile="pack.png"
authors="Xiaoyu_2009"
displayURL="https://space.bilibili.com/506597031"
description='''
本模组提供了只要但凡是一个物品都会有不死图腾的效果！
'''

[[dependencies.everything_totem]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.everything_totem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH" 